### ISSUE TITLE
[Bug] SuperStream: Is not working again...

### ISSUE THREAD

**Issue by TheWrightStuff1994** [jmir1/aniyomi-extensions#1106]
## Device information
- App version: 0.14.2.0-5857 (standard, 6485c111f, 93, 2022-12-23T18:18Z)
Android version: 10 (SDK 29)
Android build ID: QDF30.130-42-5-17
Device brand: motorola
Device manufacturer: motorola
Device name: foles
Device model: moto z4
Device product name: foles_vzw

## Source information
- Name: SuperStream
- Extension version: 13.7

## Steps to reproduce
1. Start search

### Expected behavior
The movies and shows load

### Actual behavior
Nothing appears

## Other details
![Screenshot_20221224-092344](https://user-images.githubusercontent.com/7861649/209442564-ba547613-2381-41d2-89ed-7e43514798d2.png)

**Comment by hvroun1** [comment]
It worked for a few seconds today on Dec 28th, then stopped again. What kind of bug is that? Would there be any ETA for a fix?

**Comment by hvroun1** [comment]
@TheWrightStuff1994 is it because alot of people are using the extension?

**Comment by TheWrightStuff1994** [comment]
@hvroun1 I think it's servers are either trying to run and everyone jumping on the wagon before they got the wheel on or something else...

**Comment by hvroun1** [comment]
@TheWrightStuff1994 oh I see, 
now its saying "query Failed java.net.SocketTimeoutExceptio n: failed to connect to /152.32.149.160 (port 443) from /192.168.100.16 (port 49484) after 10000ms"

I have saved a massive library using this extension because of the different HD qualities and fast loading times. The best extension ever.
I would hate to lose it all, Is there any other way to access the server without using the extension?

**Comment by TheWrightStuff1994** [comment]
@hvroun1  "Is there any other way to access the server without using the extension?" Not to my knowledge we just have to wait for SuperStream's server to come back or try using a different extension for the time being...

**Comment by hvroun1** [comment]
Understood.

**Comment by hvroun1** [comment]
Understood

**Comment by hvroun1** [comment]
@TheWrightStuff1994 understood.
